### ISSUE TITLE
Make and set profile picture

### ISSUE THREAD

**Issue by StefanieJaeger** [StefanieJaeger/ApertureTelegramBot#4]
Maybe create a new core in Source Filmmaker
http://www.sourcefilmmaker.com/

**Comment by jeremystucki** [comment]
I think telegram only allow still images

**Comment by StefanieJaeger** [comment]
I thought about a core with the little paper plane from Telegram either in it's eye or as an accessoire (like the 1# badge from Ego Core)

**Comment by StefanieJaeger** [comment]
Was resolved by @LukasHrazdil
